server:
  port: 8080

spring:
  application:
    name: Spring-Security

  datasource:
    url: jdbc:postgresql://localhost:5432/springsecurity
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
